### ISSUE TITLE
How to set API key?

### ISSUE THREAD

**Issue by Boguslaw-D** [AndraxDev/speak-gpt-web#1]
I opened https://assistant.teslasoft.org/chat but can't find the API key settings.

**Comment by AndraxDev** [comment]
Hello!

If you are using computer, click on the Quick Assistant icon at the top left corner > Settings > API Endpoint > Click on default endpoint and edit it.

If you are using mobile, start a chat and click settings icon > API endpoint > Click on default endpoint and edit it.

If there's no default endpoint the add a new one and folllowing the instructions:

1. To the label field enter OpenAI (or something else helping you recognize this endpoint)
2. To the url field enter base url (don't forget to put slash at the end of url) For example OpenAI base url is: https://api.openai.com/v1/
3. Enter your API key and click save

The you will be able to use SpeakGPT

## Important note

The following features requires exactly OpenAI endpoint: 

- Image generation using /imagine command
- Image recognition

**Comment by Boguslaw-D** [comment]
OK, thanks. I thought it was only for typing endpoint, which in my case was already set correctly, so I didn't edit it.
