### ISSUE TITLE
Incorrect Material Design version

### ISSUE THREAD

**Issue by sivert-io** [AndraxDev/speak-gpt-web#2]
Heads up that MUI is using Material Design 2 ☝🏼🤓

Ref the repositories description:

> Web version of SpeakGPT created using ReactJS and **Google Material Design 3**

I'm looking for repo's using MD3 with React to use as inspiration for my own projects :)

**Comment by AndraxDev** [comment]
I transformed MD2 to MD3 by adding customizations like small text on button, round colors, dynamic theme palette so SpeakGPT is adhearing to Material Design 3 version. You can check animations, buttons, etc and ensure SpeakGPT is themed using MD3 guidelines.

**Comment by AndraxDev** [comment]
![Screenshot_2024-06-03-18-58-08-105_com.android.chrome.jpg](https://github.com/AndraxDev/speak-gpt-web/assets/43646136/46b1dbad-3512-4926-be0a-671dc7cea5d3)


Here's is a simple example: Buttons text is not capitalized, button corner radius is completely round, button text, site background and site text uses dynamic blue theme. Dynamic harmonic theme is a feature available only on Material Design 3.

**Comment by AndraxDev** [comment]
![Screenshot_2024-06-03-19-00-49-261_org.teslasoft.assistant.jpg](https://github.com/AndraxDev/speak-gpt-web/assets/43646136/5028f90f-663b-4411-a257-03c8ff479bd5)

Another example: Floating action bar is MD3 stylized, corners are not rounded completely.

Navigation bar have an outline if item is selected and layout dimensions are from MD3.

Action bar is fully transparent.

There's no shades around elements. Flat elements is the one of the features of Material Design 3.

P.S I kindly ask you to examine the problem fully before writing blind comments. Thanks!

If you want to use MD3 then Mui is pretty enough for you. Don't pay attention on the MD version. MD2 is only the label and you are free to create custom components or modify existing. Mui is an open-source well-documented framework.

MD3 components for this project can be found in /widgets folder, dynamic the can be found in /theme folder. index.css contain styles for MD3 components based on the official Google guidelines.
